### PR TITLE
Added navigation and static pages

### PR DESCRIPTION
**Pull request by degoeym**
Solution for #7

### CODE REVIEW

**Comment by degoeym** [comment]
Holy hell I have no idea why there are so many files in this check-in.

**Comment by cartoloupe** [comment]
try removing everything in drift/\* and tmp/\* ?
also try rebasing master; since everything in drift/\* was moved to app root

**Comment by cartoloupe** [comment]
@degoeym removed those things; now it's down to 18

**Comment by cartoloupe** [comment]
:+1:

**Comment by degoeym** [comment]
Awesome. The only thing I can think of that would have caused that is I initially started the change in the master branch then switched to a feature branch. I need to work on getting into a better git flow.

**Pull request merged**
